config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :users
  resources :accounts
  resources :gendescs
  resources :items
  resources :units
  resources :transactions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entity.rb
class Entity < ApplicationRecord
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:name, :no, :frac, :unit, :street, :box, :city, :polsub, :postal, :nation, :phone, :email, :url)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(entity) do |f| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :no %>
    <%= f.number_field :no %>
  </div>

  <div class="field">
    <%= f.label :frac %>
    <%= f.text_field :frac %>
  </div>

  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :box %>
    <%= f.text_field :box %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :polsub %>
    <%= f.text_field :polsub %>
  </div>

  <div class="field">
    <%= f.label :postal %>
    <%= f.text_field :postal %>
  </div>

  <div class="field">
    <%= f.label :nation %>
    <%= f.text_field :nation %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>No</th>
      <th>Frac</th>
      <th>Unit</th>
      <th>Street</th>
      <th>Box</th>
      <th>City</th>
      <th>Polsub</th>
      <th>Postal</th>
      <th>Nation</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.name %></td>
        <td><%= entity.no %></td>
        <td><%= entity.frac %></td>
        <td><%= entity.unit %></td>
        <td><%= entity.street %></td>
        <td><%= entity.box %></td>
        <td><%= entity.city %></td>
        <td><%= entity.polsub %></td>
        <td><%= entity.postal %></td>
        <td><%= entity.nation %></td>
        <td><%= entity.phone %></td>
        <td><%= entity.email %></td>
        <td><%= entity.url %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entity.name %>
</p>

<p>
  <strong>No:</strong>
  <%= @entity.no %>
</p>

<p>
  <strong>Frac:</strong>
  <%= @entity.frac %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @entity.unit %>
</p>

<p>
  <strong>Street:</strong>
  <%= @entity.street %>
</p>

<p>
  <strong>Box:</strong>
  <%= @entity.box %>
</p>

<p>
  <strong>City:</strong>
  <%= @entity.city %>
</p>

<p>
  <strong>Polsub:</strong>
  <%= @entity.polsub %>
</p>

<p>
  <strong>Postal:</strong>
  <%= @entity.postal %>
</p>

<p>
  <strong>Nation:</strong>
  <%= @entity.nation %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @entity.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entity.email %>
</p>

<p>
  <strong>Url:</strong>
  <%= @entity.url %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>