config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :users
  resources :accounts
  resources :gendescs
  resources :items
  resources :units
  resources :transactions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gendesc.rb
class Gendesc < ApplicationRecord
end

app/controllers/gendescs_controller.rb
class GendescsController < ApplicationController
  before_action :set_gendesc, only: [:show, :edit, :update, :destroy]

  # GET /gendescs
  # GET /gendescs.json
  def index
    @gendescs = Gendesc.all
  end

  # GET /gendescs/1
  # GET /gendescs/1.json
  def show
  end

  # GET /gendescs/new
  def new
    @gendesc = Gendesc.new
  end

  # GET /gendescs/1/edit
  def edit
  end

  # POST /gendescs
  # POST /gendescs.json
  def create
    @gendesc = Gendesc.new(gendesc_params)

    respond_to do |format|
      if @gendesc.save
        format.html { redirect_to @gendesc, notice: 'Gendesc was successfully created.' }
        format.json { render :show, status: :created, location: @gendesc }
      else
        format.html { render :new }
        format.json { render json: @gendesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gendescs/1
  # PATCH/PUT /gendescs/1.json
  def update
    respond_to do |format|
      if @gendesc.update(gendesc_params)
        format.html { redirect_to @gendesc, notice: 'Gendesc was successfully updated.' }
        format.json { render :show, status: :ok, location: @gendesc }
      else
        format.html { render :edit }
        format.json { render json: @gendesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gendescs/1
  # DELETE /gendescs/1.json
  def destroy
    @gendesc.destroy
    respond_to do |format|
      format.html { redirect_to gendescs_url, notice: 'Gendesc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gendesc
      @gendesc = Gendesc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gendesc_params
      params.require(:gendesc).permit(:gendesc)
    end
end

app/helpers/gendescs_helper.rb
module GendescsHelper
end

app/views/gendescs/_form.html.erb
<%= form_for(gendesc) do |f| %>
  <% if gendesc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gendesc.errors.count, "error") %> prohibited this gendesc from being saved:</h2>

      <ul>
      <% gendesc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gendesc %>
    <%= f.text_field :gendesc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gendescs/edit.html.erb
<h1>Editing Gendesc</h1>

<%= render 'form', gendesc: @gendesc %>

<%= link_to 'Show', @gendesc %> |
<%= link_to 'Back', gendescs_path %>

app/views/gendescs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gendescs</h1>

<table>
  <thead>
    <tr>
      <th>Gendesc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gendescs.each do |gendesc| %>
      <tr>
        <td><%= gendesc.gendesc %></td>
        <td><%= link_to 'Show', gendesc %></td>
        <td><%= link_to 'Edit', edit_gendesc_path(gendesc) %></td>
        <td><%= link_to 'Destroy', gendesc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gendesc', new_gendesc_path %>

app/views/gendescs/new.html.erb
<h1>New Gendesc</h1>

<%= render 'form', gendesc: @gendesc %>

<%= link_to 'Back', gendescs_path %>

app/views/gendescs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gendesc:</strong>
  <%= @gendesc.gendesc %>
</p>

<%= link_to 'Edit', edit_gendesc_path(@gendesc) %> |
<%= link_to 'Back', gendescs_path %>