config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :users
  resources :accounts
  resources :gendescs
  resources :items
  resources :units
  resources :transactions
  resources :entities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:unit, :factor, :m, :kg, :s, :a, :k, :cd, :mol)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(unit) do |f| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>

  <div class="field">
    <%= f.label :factor %>
    <%= f.text_field :factor %>
  </div>

  <div class="field">
    <%= f.label :m %>
    <%= f.number_field :m %>
  </div>

  <div class="field">
    <%= f.label :kg %>
    <%= f.number_field :kg %>
  </div>

  <div class="field">
    <%= f.label :s %>
    <%= f.number_field :s %>
  </div>

  <div class="field">
    <%= f.label :a %>
    <%= f.number_field :a %>
  </div>

  <div class="field">
    <%= f.label :k %>
    <%= f.number_field :k %>
  </div>

  <div class="field">
    <%= f.label :cd %>
    <%= f.number_field :cd %>
  </div>

  <div class="field">
    <%= f.label :mol %>
    <%= f.number_field :mol %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Unit</th>
      <th>Factor</th>
      <th>M</th>
      <th>Kg</th>
      <th>S</th>
      <th>A</th>
      <th>K</th>
      <th>Cd</th>
      <th>Mol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.unit %></td>
        <td><%= unit.factor %></td>
        <td><%= unit.m %></td>
        <td><%= unit.kg %></td>
        <td><%= unit.s %></td>
        <td><%= unit.a %></td>
        <td><%= unit.k %></td>
        <td><%= unit.cd %></td>
        <td><%= unit.mol %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit:</strong>
  <%= @unit.unit %>
</p>

<p>
  <strong>Factor:</strong>
  <%= @unit.factor %>
</p>

<p>
  <strong>M:</strong>
  <%= @unit.m %>
</p>

<p>
  <strong>Kg:</strong>
  <%= @unit.kg %>
</p>

<p>
  <strong>S:</strong>
  <%= @unit.s %>
</p>

<p>
  <strong>A:</strong>
  <%= @unit.a %>
</p>

<p>
  <strong>K:</strong>
  <%= @unit.k %>
</p>

<p>
  <strong>Cd:</strong>
  <%= @unit.cd %>
</p>

<p>
  <strong>Mol:</strong>
  <%= @unit.mol %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>